export const STOCK_MOVEMENT_TYPES = {
  INITIAL_STOCK: 'INITIAL_STOCK',
  ALLOCATE_TO_MARKETPLACE: 'ALLOCATE_TO_MARKETPLACE',
  RETURN_TO_WAREHOUSE: 'RETURN_TO_WAREHOUSE',
  SALE: 'SALE',
  ADJUSTMENT: 'ADJUSTMENT',
} as const;

export type StockMovementType = (typeof STOCK_MOVEMENT_TYPES)[keyof typeof STOCK_MOVEMENT_TYPES];
